### ISSUE TITLE
[EN] l10n: Source strings need to be in english

### ISSUE THREAD

**Issue by rakekniven** [baimard/gestion#4]
The resource has been added to Transifex and now translators start to translate.

One thing has been reported multiple times today:
Many of the source strings are in french.

That is not valid. All source strings need to be in english.

Please change them to english.
Currently I locked the resource "gestion" for all languages/translators.
I will unlock it as soon as changes are done.

Thank you.

**Comment by baimard** [comment]
I had see the problem when you had change .tx/config in fr to en.

I will modified all quickly.

Thank you for report !

**Comment by Valdnet** [comment]
I also propose to add multilingualism in PHP files in the `templates` directory so that the application is fully translated into other languages.
Here, for example: 
https://github.com/baimard/gestion/blob/8f86fbe60f2c7fcbc1ec04cb6a2face6d963a158/templates/settings/index.php#L9-L10
https://github.com/baimard/gestion/blob/8f86fbe60f2c7fcbc1ec04cb6a2face6d963a158/templates/navigation/index.php#L2
e.t.c.

**Comment by Valdnet** [comment]
I also propose to add multilingualism for PHP files in the "templates" directory so that the application is fully translated into different languages.
For example here:
https://github.com/baimard/gestion/blob/8f86fbe60f2c7fcbc1ec04cb6a2face6d963a158/templates/settings/index.php#L9-L10
https://github.com/baimard/gestion/blob/8f86fbe60f2c7fcbc1ec04cb6a2face6d963a158/templates/navigation/index.php#L2
e.t.c.

**Comment by baimard** [comment]
Yes it's planned, i'm alone on this project. 

I started without translation idea, I need time to set all translatable :)

Give me some time please :)

**Comment by baimard** [comment]
I think 90% of the application is translated and I have applied all of your recommandations.

tell me if it's good for you.

**Comment by rakekniven** [comment]
You are fast.
Looks pretty good. 👍 

Some strings are starting with lowercase, most of them in uppercase. 
As I am not a user of your app I cannot judge if this is ok.
Maybe we have to adapt some of this little things. 
But for now I will enable resource at Transifex again.

**Comment by baimard** [comment]
> Some strings are starting with lowercase, most of them in uppercase.

that's because some strings are sentence and others are type of button.

I was fast because you are fast too ! So thank you for all of your help. This application is very important for me and I think it's really useful for the community. Lots of european peoples want to start a Micro-entreprise in France. So I'm going to add a documentation to open Micro Entreprise in France. And the application with the documentation looks pretty goods to start commercial activity in France.

**Comment by baimard** [comment]
@rakekniven is possible that I validate the french translation in transifex ?

**Comment by rakekniven** [comment]
What is your username at Transifex?

**Comment by baimard** [comment]
baimard :)

**Comment by baimard** [comment]
> Added you as reviewer for french. Please only take care of your own resource.
> Before reviewing others contact your french reviewer collegues first.

taken into account, do not hesitate to send me email in case of problem.

**Comment by rakekniven** [comment]
Some variables e.g. "infoEmpty" are not english. Do you want these strings be translated?

![grafik](https://user-images.githubusercontent.com/2069590/128179625-2a3c09e1-0ccb-4a39-a348-5d3ec764c707.png)

If yes, they need to be adapted.

**Comment by baimard** [comment]
Yes, I need to adapt this.

This is in my todo

- [ ]  change translation string I.E. set strings instead of var for Datatable object.

**Comment by rakekniven** [comment]
> Is there communication channel for all of reviewer of transifex ?

No, Transifex is poor if it comes to community/group communication.

**Comment by rakekniven** [comment]
Please see my PRs.

**Comment by baimard** [comment]
According to the documentation I need to have strings formated, so I will decompose the string.

https://datatables.net/manual/i18n

**Comment by baimard** [comment]
Done,

I wait for the next batch of transifex before closing

**Comment by rakekniven** [comment]
Let us close here and stay with the single issues I already filed.
